### ISSUE TITLE
LMI maintainer

### ISSUE THREAD

**Issue by Lowxorx** [Spark-Rom/official_devices#100]
## Device you want to apply for
```
POCO F2 Pro (lmi)
```

## Device tree sources

```
https://github.com/Lowxorx/android_device_xiaomi_lmi/tree/pyro
https://github.com/Lowxorx/android_device_xiaomi_sm8250-common/tree/pyro
https://gitlab.com/Lowxorx/vendor_xiaomi
https://github.com/macka69/kernel_xiaomi_sm8250-1/tree/next7-lmi1009
```

## Link to the platform where you have released your unofficial build
```
https://t.me/SparkOSChannel
```

## Other ROM's you maintain officially or unofficially
```
Corvus, Awaken
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
lowxorx
```

**Comment by ghost** [comment]
Your commits is being signed with the email "lowxorx@lahan.fr" and it seems that it's not linked to your account, because of that your commits is signed by a person that doesn't exist:D

**Comment by Lowxorx** [comment]
> Your commits is being signed with the email "[lowxorx@lahan.fr](mailto:lowxorx@lahan.fr)" and it seems that it's not linked to your account, because of that your commits is signed by a person that doesn't exist:D make rebase wem ??.

My email settings were screwed on gh. It's fixed.

**Comment by ghost** [comment]
> > Your commits is being signed with the email "[lowxorx@lahan.fr](mailto:lowxorx@lahan.fr)" and it seems that it's not linked to your account, because of that your commits is signed by a person that doesn't exist:D make rebase wem ??.
> 
> My email settings were screwed on gh. It's fixed.

Great! Looks good! You've already been accepted, right?

**Comment by Lowxorx** [comment]
> > > Your commits is being signed with the email "[lowxorx@lahan.fr](mailto:lowxorx@lahan.fr)" and it seems that it's not linked to your account, because of that your commits is signed by a person that doesn't exist:D make rebase wem ??.
> > 
> > 
> > My email settings were screwed on gh. It's fixed.
> 
> Great! Looks good! You've already been accepted, right?

Yes I was already a Spark A11/ A12 maintainer :)

**Comment by ghost** [comment]
> > > > Your commits is being signed with the email "[lowxorx@lahan.fr](mailto:lowxorx@lahan.fr)" and it seems that it's not linked to your account, because of that your commits is signed by a person that doesn't exist:D make rebase wem ??.
> > > 
> > > 
> > > My email settings were screwed on gh. It's fixed.
> > 
> > 
> > Great! Looks good! You've already been accepted, right?
> 
> Yes I was already a Spark A11/ A12 maintainer :)

Nicee! Close issue

**Comment by spkal01** [comment]
@enzo19976 mate could you plz leave the official process to us ?

**Comment by ghost** [comment]
> @enzo19976 mate could you plz leave the official process to us ?

Ok, srryy

**Comment by whyredfire** [comment]
Hi, here are a few things you can do.
- Pick ItsVixano/android_device_xiaomi_msm8953-common@d72310ec08a7f44b052a4a1156ad7847883a915b
- Drop RemovePackages, SparkOS doesn't have those packages by default
- Fix authorship for the folloing commit Lowxorx/android_device_xiaomi_sm8250-common@08d6809a8c42baeb9a862951c137c21e2f045cac

**Comment by Lowxorx** [comment]
> 

I adapted this commit ([https://github.com/Lowxorx/android_device_xiaomi_sm8250-common/commit/08d6809a8c42baeb9a862951c137c21e2f045cac](https://github.com/Lowxorx/android_device_xiaomi_sm8250-common/commit/08d6809a8c42baeb9a862951c137c21e2f045cac)) from [https://github.com/venom-trees/device-xiaomi-sm8250/commit/db45020e2c9e64fb4866c4589ad0db132ab0495f](https://github.com/venom-trees/device-xiaomi-sm8250/commit/db45020e2c9e64fb4866c4589ad0db132ab0495f), should I just have to put the commit id in the commit message?

I'll pick the reorder libs thing & fix RemovePackage, thanks for the suggestion

**Comment by whyredfire** [comment]
Sure, just mention something like, inspired from and then put commit id.

**Comment by Lowxorx** [comment]
> Sure, just mention something like, inspired from and then put commit id.

Done.
