### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Mikdadali** [Spark-Rom/official_devices#101]
## Device you want to apply for
Xiaomi 11 lite NE 5g
Your device name and codename
lisa

## Device tree sources

```
https://github.com/Mikdadali/device_xiaomi_lisa
https://github.com/Mikdadali/kernel_xiaomi_lisa
https://github.com/Mikdadali/vendor_xiaomi_lisa-12
```

## Link to the platform where you have released your unofficial build
```
[Insert here](https://t.me/Xiaomi11LiteNEUpdates)
```

## Other ROM's you maintain officially or unofficially
```
Superior OS - Officially
Corvus - Unofficially
PEX - Unofficially
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@ali_171821_
```

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
