### ISSUE TITLE
New maintainer for sweet [redmi note 10 pro]

### ISSUE THREAD

**Issue by ghost** [Spark-Rom/official_devices#102]
## Device you want to apply for
```
Your device name and codename
``` redmi note 10 pro (sweet)

## Device tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```
https://github.com/kangeraarav/device_xiaomi_sweet
https://github.com/kangeraarav/device_xiaomi_sm6150-common
https://github.com/kangeraarav/vendor_xiaomi
https://github.com/Sm6150-Sweet/kernel_xiaomi_sm6150
```

## Link to the platform where you have released your unofficial build
```
Insert here testing but booted
```

## Other ROM's you maintain officially or unofficially
```
Insert here project blaze, eternity os, porject flexo
```

## Bugs on unofficial build
```
None 
```

## How long have you been building for?
```
Weeks/Months/Years 1.5 year
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing. yes
```

## Are you using a prebuilt kernel? If yes, why?
```
No. no
```

## Contact
### Telegram username  @aarav_x
```
Your Telegram username
``` @aarav_x

**Comment by ghost** [comment]
@whyredfire @spkal01 check once

**Comment by kangeraarav** [comment]
i had tested all stuffs in my dt.. they were private so i worked on them yesterday and today

**Comment by ghost** [comment]
default branch is T

**Comment by whyredfire** [comment]
Hi, seems like you've reset the top few commits from https://github.com/Sm6150-Sweet/device_xiaomi_sm6150/commits/13.0 and repicked them with no changes whatsoever. I also noticed that you kanged one of these, kangeraarav/device_xiaomi_sm6150-common@0abf6b89bd0b223c1c125c5b2bee4addf6645760.
The same is true for sweet specific tree as well, other than that, you've enabled F2FS compression yesterday kangeraarav/device_xiaomi_sweet@fb40df910a400504c55b5ab225810fcd68ed5c2c and dropped it here today kangeraarav/device_xiaomi_sweet@3e60941ee3d72521804e406805cf0c1a1ad1df48 which again is a kang of Sm6150-Sweet/device_xiaomi_sweet@eab18f85c5e3df6d7c293115cf3e915a05db0466.

For the above listed reasons, you've been rejected.

**Comment by ghost** [comment]
See i hadn't kanged that livedisplay one,
I had dropped that service in my old dt 1 month ago

**Comment by kangeraarav** [comment]
And if i giv authorship then am i acc

**Comment by kangeraarav** [comment]
Ahh sir I didn't kanged , I dropped livedisplay service on my old dt 1
month ago
