### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by MetoisTaken** [Spark-Rom/official_devices#107]
## Device you want to apply for
```
Xiaomi Mi A1 (tissot)
```

## Device tree sources

```
https://github.com/MetoIsTaken/device_xiaomi_tissot_t/tree/13-Spark
https://github.com/MetoIsTaken/device_xiaomi_msm8953-common_t/tree/13-Spark
https://github.com/MetoIsTaken/vendor_xiaomi_tissot_t
https://github.com/MetoIsTaken/vendor_xiaomi_msm8953-common_t
https://github.com/MetoIsTaken/kernel_xiaomi_tissot
```

## Link to the platform where you have released your unofficial build
```
https://forum.xda-developers.com/f/xiaomi-mi-a1-roms-kernels-recoveries-other-de.7048/
https://t.me/Meto_Kitchen
https://t.me/MiA1_Global
```

## Other ROM's you maintain officially or unofficially
```
ArrowOS 13 Unofficial
SparkOS 13 Unofficial
CorvusOS Unofficial (EOL)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
7 Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
MetoIsTaken
```

**Comment by whyredfire** [comment]
Hi, rewrite commit messages properly with the following format on your common tree **<path/repository name reference>: <Commit title that MUST be a basic explanation for its content>**. Furthermore squash the following commits, MetoIsTaken/device_xiaomi_msm8953-common_t@e5c002b7acbc90beb5ffd90d5cf37a52fb4407c3 & MetoIsTaken/device_xiaomi_msm8953-common_t@2d71f07927ce0c3b9f1fd52af822f157cbb0f596.

**Comment by MetoisTaken** [comment]
> Hi, rewrite commit messages properly with the following format on your common tree **<path/repository name reference>: **. Furthermore squash the following commits, [MetoIsTaken/device_xiaomi_msm8953-common_t@e5c002b](https://github.com/MetoIsTaken/device_xiaomi_msm8953-common_t/commit/e5c002b7acbc90beb5ffd90d5cf37a52fb4407c3) & [MetoIsTaken/device_xiaomi_msm8953-common_t@2d71f07](https://github.com/MetoIsTaken/device_xiaomi_msm8953-common_t/commit/2d71f07927ce0c3b9f1fd52af822f157cbb0f596).

Edited.

**Comment by whyredfire** [comment]
MetoIsTaken/device_xiaomi_msm8953-common_t@4e66dc2148cf5355877407f151b4f822e8b14a73
MetoIsTaken/device_xiaomi_msm8953-common_t@ee606f0b544a0cf1b3bfa5c0758651eac8983543
MetoIsTaken/device_xiaomi_msm8953-common_t@4ee4c6c7be0fa12a24623d0afa794e7d22602d23
MetoIsTaken/device_xiaomi_msm8953-common_t@a1327fbe9009ee59576ac91bb035e2cce85c3c0c

**Comment by MetoisTaken** [comment]
https://github.com/MetoIsTaken/device_xiaomi_msm8953-common_tiramisu here's the new tree.
