### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by JuanTamadski** [Spark-Rom/official_devices#112]
## Device you want to apply for
```
Asus 5z - Z01R
```

## Device tree sources

```
https://github.com/JuanTamadski/android_device_asus_Z01R Android 12, https://github.com/JuanTamadski/Z01R Android 13
https://github.com/JuanTamadski/kernel_z01r
https://github.com/JuanTamadski/vendor_asus
```

## Link to the platform where you have released your unofficial build
```
[Insert here](https://forum.xda-developers.com/t/rom-unofficial-spark-rom-spark-12-1-z01r.4500071/)
```

## Other ROM's you maintain officially or unofficially
```
(https://forum.xda-developers.com/t/rom-unofficial-aicp-s12-1-z01r.4493557/
https://forum.xda-developers.com/t/rom-unofficial-12-1-project-blaze-v1-4-z01r.4490055/)
```

## Bugs on unofficial build
```
[None]
```

## How long have you been building for?
```
1 month
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I believe I violated something about authorship because I am still familiarizing with github.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Juantamadski
```

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
