### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by kibria5** [Spark-Rom/official_devices#113]
## Device you want to apply for
```
Redmi Note 7 Pro (violet)
```

## Device tree sources

```
https://github.com/kibria5/android_device_xiaomi_violet.git
https://github.com/kibria5/android_kernel_xiaomi_violet.git
https://github.com/kibria5/android_vendor_xiaomi_violet.git
```

## Link to the platform where you have released your unofficial build
```
https://forum.xda-developers.com/t/rom-13-violet-unofficial-spark-os-13-15-10-22.4505813/
https://t.me/RedmiNote7ProChannel/2174
https://t.me/violetofficialupdates/4569
```

## Other ROM's you maintain officially or unofficially
```
PixelExtended A13 Official
project zephyrus A13 Official
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 Year
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/kibria5
```

**Comment by kibria5** [comment]
I opened this issue 9 days ago but under review from 8 days ago why

**Comment by whyredfire** [comment]
Fix authorship for the following commits
kibria5/android_device_xiaomi_violet@accd2dcd7d5ab25c1ef9c1575c217d3834eb6440
kibria5/android_device_xiaomi_violet@6bae79caf8463b3ba4f7621e98c0e0a9aa3905ef

Squash the following
kibria5/android_device_xiaomi_violet@59b3418bd21875c34c9b4fa151c302c132cf84ac
kibria5/android_device_xiaomi_violet@0ad034486b169e82091ad643a09769cc609a9a51
kibria5/android_device_xiaomi_violet@ded598999364b6b16008723bb554201a8b3bae7f

**Comment by kibria5** [comment]
Thanks for reply, Please check now, I've edited

**Comment by kibria5** [comment]
> Fix authorship for the following commits [kibria5/android_device_xiaomi_violet@accd2dc](https://github.com/kibria5/android_device_xiaomi_violet/commit/accd2dcd7d5ab25c1ef9c1575c217d3834eb6440) [kibria5/android_device_xiaomi_violet@6bae79c](https://github.com/kibria5/android_device_xiaomi_violet/commit/6bae79caf8463b3ba4f7621e98c0e0a9aa3905ef)
> 
> Squash the following [kibria5/android_device_xiaomi_violet@59b3418](https://github.com/kibria5/android_device_xiaomi_violet/commit/59b3418bd21875c34c9b4fa151c302c132cf84ac) [kibria5/android_device_xiaomi_violet@0ad0344](https://github.com/kibria5/android_device_xiaomi_violet/commit/0ad034486b169e82091ad643a09769cc609a9a51) [kibria5/android_device_xiaomi_violet@ded5989](https://github.com/kibria5/android_device_xiaomi_violet/commit/ded598999364b6b16008723bb554201a8b3bae7f)

i already edited check please

**Comment by whyredfire** [comment]
Why are you trying to remove a lot of non existent packages in remove_packages?
Delete duplicate definition for SystemUI dex preopt, its already done in vendor [here](https://github.com/Spark-Rom/platform_vendor_spark/blob/27aa5257351542c3cf0927203785d8a7f1b63ef5/config/common.mk#L164)
Update lineage camera package name [here](https://github.com/kibria5/android_device_xiaomi_violet/blob/a581bf3e19c4dbb893a2a4f5504e7265030abdc5/product.prop#L39), lineage snapcam is dead now

**Comment by kibria5** [comment]
> Why are you trying to remove a lot of non existent packages in remove_packages? Delete duplicate definition for SystemUI dex preopt, its already done in vendor [here](https://github.com/Spark-Rom/platform_vendor_spark/blob/27aa5257351542c3cf0927203785d8a7f1b63ef5/config/common.mk#L164) Update lineage camera package name [here](https://github.com/kibria5/android_device_xiaomi_violet/blob/a581bf3e19c4dbb893a2a4f5504e7265030abdc5/product.prop#L39), lineage snapcam is dead now

now, check please.

**Comment by kibria5** [comment]
> Why are you trying to remove a lot of non existent packages in remove_packages? Delete duplicate definition for SystemUI dex preopt, its already done in vendor [here](https://github.com/Spark-Rom/platform_vendor_spark/blob/27aa5257351542c3cf0927203785d8a7f1b63ef5/config/common.mk#L164) Update lineage camera package name [here](https://github.com/kibria5/android_device_xiaomi_violet/blob/a581bf3e19c4dbb893a2a4f5504e7265030abdc5/product.prop#L39), lineage snapcam is dead now

check now
