### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by unsatifsed27** [Spark-Rom/official_devices#114]
## Device you want to apply for
```
Your device name and codename
Redmi Note 10 Pro (sweet)

```
## Device tree sources
```
https://github.com/unsatifsed27/device_xiaomi_sweet.git
https://github.com/shashank1439/kernel_xiaomi_sm6150.git
https://github.com/unsatifsed27/vendor_xiaomi_sweet.git
```

## Link to the platform where you have released your unofficial build
```
Not share just build my self
```

## Other ROM's you maintain officially or unofficially
```
Superior (Official)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 Years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
Your Telegram username
unsatifsed27
```

**Comment by whyredfire** [comment]
Hi, here are a few things you need to do.
- This unsatifsed27/device_xiaomi_sweet@e00f5fa5b9045cd217d4d38c9deffdfc141bdf8a isn't allowed, we spoof Google Photos to Pixel 1 for unlimited high quality backup.
- Provide proper authorship for this commit unsatifsed27/device_xiaomi_sweet@63f31bf22ceda60e71a828fe1134f08608b42a49
- Are you sure about [this](https://github.com/unsatifsed27/device_xiaomi_sweet/commit/823e12876610595adf9171b9edb9bbbbe5d13c02#diff-2b95b9fc8753c479733193532b0c8a3d9193a2233f3f61ffa444e7e0772ce880R27)?

**Comment by unsatifsed27** [comment]
Thnks for riview, i edited

**Comment by unsatifsed27** [comment]
Please check again, I've edited it again
