### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by BitsAndBytes-dev** [Spark-Rom/official_devices#115]
## Device you want to apply for
```
POCO X3 Pro (vayu)
```

## Device tree sources

```
https://github.com/Spark-Devices/android_device_xiaomi_vayu
https://github.com/Spark-Devices/android_vendor_xiaomi_vayu
https://github.com/Jebaitedneko/android_kernel_xiaomi_vayu
```

## Link to the platform where you have released your unofficial build
```
https://t.me/PocoX3ProUpdates/1268
```

## Other ROM's you maintain officially or unofficially
```
Corvus OS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 Years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
thepsambit
```

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
