### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by bishwofic** [Spark-Rom/official_devices#116]
## Device you want to apply for
```
Redmi Note 8 Pro (Begonia)
```

## Device tree sources

```
https://github.com/bishwofic/android_device_redmi_begonia
https://github.com/Nova-Kernels/kernel_xiaomi_mt6785-a13
https://github.com/bishwofic/android_vendor_redmi_begonia
```

## Link to the platform where you have released your unofficial build
```
https://t.me/RedmiNote8ProUpdates/1198
```

## Other ROM's you maintain officially or unofficially
```
CherishOS - Officially
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1+ Year
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@bishwofic
```

**Comment by whyredfire** [comment]
1. Looks like you've just reset and re-picked from https://github.com/begonia-dev/android_device_redmi_begonia.
2. Your tree isn't even buildable for Spark Rom.
