### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by bishwofic** [Spark-Rom/official_devices#117]
## Device you want to apply for
```
Xiaomi Redmi Note 8 Pro
```

## Device tree sources
```
Device: https://github.com/bishwofic/android_device_redmi_begonia
Vendor: https://github.com/Trinity-ROMS/android_vendor_redmi_begonia
Kernel: https://github.com/Nova-Kernels/kernel_xiaomi_mt6785-a13
```

## Link to the platform where you have released your unofficial build
```
https://forum.xda-developers.com/t/rom-13-0-unofficial-spark-os-v13-1-begonia.4508991/
https://t.me/RedmiNote8ProUpdates/1198
https://t.me/BegoniaUpdateIndonesia/1752
```

## Other ROM's you maintain officially or unofficially
```
CherishOS: Official
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1+ Year
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@bishwofic
```

**Comment by whyredfire** [comment]
https://github.com/Spark-Rom/official_devices/issues/116#issuecomment-1285004414

**Comment by bishwofic** [comment]
I don't mean to start any issue but the tree is certainly buildable for spark and there are well over 50 commits after the reset pick.
