### ISSUE TITLE
New maintainer RMX3360

### ISSUE THREAD

**Issue by itsxrp** [Spark-Rom/official_devices#119]
## Device you want to apply for
```
realme GT Master Edition RMX3360
```

## Device tree sources

```
https://github.com/itsxrp/device_oplus_sm8350-common
https://github.com/itsxrp/device_oplus_RMX3360
https://github.com/itsxrp/android_kernel_oplus_sm8350
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/xrp-roms/files/TEST/
```

## Other ROM's you maintain officially or unofficially
```
Project Elixir
Ancient OS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1.5Years+
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram usernames
```
itsXRP
```

**Comment by whyredfire** [comment]
Hi there, while reviewing your trees we felt like you don't actually realize what you're doing. This commit for example, do you realize whats ih8sn for? (itsxrp/device_oplus_sm8350-common@f1a75ce56f9f2ae35ca8dbda57b5d0bf2ccce797).

You can apply again in the future whenever you've gained more experience.

**Comment by itsxrp** [comment]
Really rejected due to this ih8sn commit?
And whats actually wrong with it.Can u please explain a bit.

Thanks
