### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by bittencourtjulival** [Spark-Rom/official_devices#121]
## Device you want to apply for
```
MI MIX 2S (polaris)
```

## Device tree sources

```
https://github.com/bittencourtjulival/android_device_xiaomi_polaris
https://github.com/bittencourtjulival/android_device_xiaomi_sdm845-common
https://github.com/bittencourtjulival/vendor_xiaomi_polaris
https://github.com/bittencourtjulival/vendor_xiaomi_sdm845-common
https://github.com/bittencourtjulival/android_kernel_xiaomi_sdm845
```

## Link to the platform where you have released your unofficial build
```
https://t.me/xda_mi_mix_2s
```

## Other ROM's you maintain officially or unofficially
```
none, I am returning to activities after medical treatment, and I intend to keep only SparkOS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@bittencourtjulival
```

**Comment by whyredfire** [comment]
Hi, please consider cleaning up your RemovePackages list as it contains a lot of packages which aren't being shipped like OPScreenRecord.
