### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by miwu04** [Spark-Rom/official_devices#122]
## Device you want to apply for
```
Xiaomi 11 (venus)
```

## Device tree sources

```
https://github.com/miwu04/device_xiaomi_venus/tree/SparkOS
https://github.com/miwu04/device_xiaomi_sm8350-common
https://github.com/miwu04/kernel_xiaomi_venus
https://gitlab.com/jjpprrrr/prelude-clang
https://github.com/miwu04/vendor_xiaomi_venus
https://github.com/miwu04/vendor_xiaomi_sm8350-common
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_venus-firmware
```

## Link to the platform where you have released your unofficial build
```
https://t.me/mi11dev
```

## Other ROM's you maintain officially or unofficially
```
xDroid
BlissROM (not release)
SparkOS (not release)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
3 mon
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
miwu04
```

**Comment by whyredfire** [comment]
Hi, while reviewing your trees/ GitHub account we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
