### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by megafire91** [Spark-Rom/official_devices#123]
## Device you want to apply for
```
Nokia 8 (NB1) > this is a msm8998 qualcomm sdm835 device.
```

## Device tree sources

```
https://github.com/megafire91/device_nokia_NB1_T/tree/spark13
https://github.com/megafire91/kernel_nokia_msm8998
https://github.com/megafire91/vendor_nokia_NB1
```

## Link to the platform where you have released your unofficial build
```
https://t.me/c/1415115863/36515
```

## Other ROM's you maintain officially or unofficially
```
AncientOS (Official) > https://forum.xda-developers.com/t/rom-12-1-treble-official-vanilla-gapps-ancientrom-society-weaboo-v6-4-for-nokia-8-nb1.4395963/
CherishOS (Unofficial) > https://forum.xda-developers.com/t/cherishos-v4-2-13-gapps-vanilla-nb1-unofficial.4508647/
```

## Bugs on unofficial build
```
Applies to both official & unofficial builds: 
- Loudspeaker on calls has a slight echo on carrier builds due to volume to loud, apps such as telegram/whatsapp work fine as volume can be reduced, however all call audio is working
- Camera recording with fluence creates a wierd on/off effect sometimes with audio, audio itself however works fine
- Wifi signal is slightly weaker than stock
- Gcam ports crash on android 13+ builds only, they work fine on A12.
Remarks: the above bug faults are still unknown

```

## How long have you been building for?
```
2 Years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
yes, I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No we are using a ported umbrella kernel, as this device is a special case that was trebilized through a partition hack & vendor was built from scratch (though i forked it, the original developer emufan4568 & i work together, he tought me how to maintain roms).
```

### Telegram username
```
@marceldossantos91
```

Special remarks about this device: 
- Nokia 8 was never an official treble supported device & development of stock rom has ended with android Pie, as such as we made a treble hack and took a partition table from the A1N (closest device to ours, 90% similar) and built a vendor from the ground up for it
- as such, we had to use P, Q & R blobs from various devices (NB1,A1N & DDV) to make our device work
- our bluetooth is unable to operate with AOSP stack, QTI is a requirement for our BT to work, however when QTI is present there are no known bluetooth issues
- our device requires a custom display hal, as we are using R display HAL from SDM660 (in my device tree already under qcom-caf) 
- we require some additional audio HAL that the source/tree also requests, i can however add this to the device tree most likely
- Device currently has 3 official roms, pixel experience, Xdroid & AncientOS, and all of us work on our trees together (this is the reason my trees are forked)

**Comment by whyredfire** [comment]
Hi, unfortunately your application has been rejected.

We couldn't see much of what we consider a reasonable experience by looking at your trees.
- Commit history is really messed up
![image](https://user-images.githubusercontent.com/72072109/208317308-9f690307-2ce0-4c17-84a7-bbec3ed1d21d.png)
![image](https://user-images.githubusercontent.com/72072109/208317385-fa538acb-6f69-466c-8831-c10321eccd96.png)

- Idk whats this megafire91/device_nokia_NB1_T@ef75d35b84fc0d44e2b188c384ae77f450a16159

You can apply again in the future whenever you've gained more experience.

**Comment by megafire91** [comment]
Good Day.

Please note the commits errors were due to a pc error, when i force pushed
it messed up a few times so i had to fix them, as i already had a working
tree for cherish, i simply used my cherish tree to build spark.

Kindly join our NB1 group:
https://t.me/HMD_Nokia_8

And see for yourself the work i have done & feel free to ask the many
people & other devs about my contributions.

I also explained i fork my trees & the device special circumstances in my
post.

I ask you to please reconsider, besides needing QTI to make SparkOS work
for us, we are at stable status with the other A12 & 13 builds i do.

Also feel free to check my nokia 8 xda, you will see im a recognized
contributer.

Thank you.
