### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by sayann70** [Spark-Rom/official_devices#125]
## Device you want to apply for
```
Redmi Note 11 (spes)
```

## Device tree sources

```
https://github.com/sayann70/device_xiaomi_spes
https://github.com/sayann70/kernel_xiaomi_spes_header
https://github.com/sayann70/vendor_xiaomi_spes
```

## Link to the platform where you have released your unofficial build
```
https://t.me/RedmiNote11_Updates/163
```

## Other ROM's you maintain officially or unofficially
```
Project Blaze officially
```

## Bugs on unofficial build
```
wifi-calling
```

## How long have you been building for?
```
6 months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes,because till now there is no kernel sources for spes 
released by xiaomi 
```

### Telegram username
```
sayann70
```

**Comment by whyredfire** [comment]
Hey, we reviewed your trees, here's a few things you can do.

- Consider reverting them
sayann70/device_xiaomi_spes@a6968630f6f15e45bc8c11ced046e52012c74086
sayann70/device_xiaomi_spes@82d6727b84c9b344fffbfe05ea5fa0671e06486c (useless for AOSP ROMs)
sayann70/device_xiaomi_spes@83eff0cbb3cddbd1f6d15cca8feb5307f8971cc0
sayann70/device_xiaomi_spes@ba567ff23007925ff66897a7f4808c133f202ba1
sayann70/device_xiaomi_spes@f393ee3d01e867fe4fe9867b7a657985414ed62e
- Drop wildcard [here](https://github.com/sayann70/device_xiaomi_spes/blob/a39b84e3a8ced107f15bfb5bddbe60c7a16001e3/BoardConfig.mk#L124-L128) and inherit Spark's hidl manifest if required from [here](https://github.com/Spark-Rom/platform_vendor_spark/blob/pyro/config/device_framework_matrix.xml).
- Spark-ROM uses `WITH_GAPPS` for GApps inclusion, update that in your BoardConfig makefile
- Move livedisplay package to device.mk from [here](https://github.com/sayann70/device_xiaomi_spes/blob/a39b84e3a8ced107f15bfb5bddbe60c7a16001e3/spark_spes.mk#L35-L37).

**Comment by sayann70** [comment]
I have done all the changes you mentioned, please check on it and see if I have done everything correctly or not.

**Comment by whyredfire** [comment]
Squash all the reverts related to props, instead of importing the whole device framework manifest, you can inherit it directly from `vendor/spark/config/device_framework_matrix.xml`. sayann70/device_xiaomi_spes@f89691985136568b4b589d32e08fa2099ea46523, this isn't what  I meant, update gapps flag [here](https://github.com/sayann70/device_xiaomi_spes/blob/ce3df5a6761d7abc00332b85aff401380dc55464/BoardConfig.mk#L188) instead.

**Comment by sayann70** [comment]
I have done the changes you mentioned , and i have removed the commits related to props. please check if everything is correct this time.
