### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by kssrao13882** [Spark-Rom/official_devices#126]
## Device you want to apply for
```
Realme 5 Pro - RMX1971
```

## Device tree sources

```
https://github.com/kssrao13882/device_realme_RMX1971-A13
https://github.com/kssrao13882/device_realme_sdm710-common_A13
https://gitlab.com/kssrao13882/kernel_realme_sdm710
https://gitlab.com/kssrao13882/vendor_realme_RMX1971
https://gitlab.com/kssrao13882/vendor_realme_sdm710-common
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Realme5Pro_Downloads/1806
```

## Other ROM's you maintain officially or unofficially
```
riceDroid, Elixir and Xtended Official
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1.5 Years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
kssrao13882
```

**Comment by whyredfire** [comment]
Hey, we reviewed your trees and here's a few things you can do.

- First and foremost, drop RemovePackages. It has a LOT of packages that are not being shipped in the first place, your device can handle the rest very easily.
- [This ](https://github.com/kssrao13882/device_realme_sdm710-common_A13/blob/1fab803bd2dd5ee0dc09cd9a2a00d29f442ddc09/sdm710.mk#L253-L255)is being copied from our vendor already, you can drop it from device tree.
- While this won't make a difference, but you should keep your [packages ](https://github.com/kssrao13882/device_realme_sdm710-common_A13/blob/1fab803bd2dd5ee0dc09cd9a2a00d29f442ddc09/sdm710.mk#L500)arranged.

**Comment by kssrao13882** [comment]
> Hey, we reviewed your trees and here's a few things you can do.
> 
> * First and foremost, drop RemovePackages. It has a LOT of packages that are not being shipped in the first place, your device can handle the rest very easily.
> * [This ](https://github.com/kssrao13882/device_realme_sdm710-common_A13/blob/1fab803bd2dd5ee0dc09cd9a2a00d29f442ddc09/sdm710.mk#L253-L255)is being copied from our vendor already, you can drop it from device tree.
> * While this won't make a difference, but you should keep your [packages ](https://github.com/kssrao13882/device_realme_sdm710-common_A13/blob/1fab803bd2dd5ee0dc09cd9a2a00d29f442ddc09/sdm710.mk#L500)arranged.

The suggestions have been carried out:
. https://github.com/kssrao13882/device_realme_RMX1971-A13/commit/07e481195d255bb587a40df366f2e3f094a5ee6c
. https://github.com/kssrao13882/device_realme_sdm710-common_A13/commit/7cb6b9b58ebbfd4cdc389f5d050a5d3d71b27418
