### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by hipexscape** [Spark-Rom/official_devices#129]
## Device you want to apply for
```
Redmi 9 and Poco M2 (lava)
```

## Device tree sources

```
https://github.com/deadaf5/android_xaiomi_lancelot/tree/spark
https://github.com/deadaf5/android_kernel_xiaomi_mt6768
https://github.com/deadaf5/proprietary_vendor_xiaomi_lancelot
```

## Link to the platform where you have released your unofficial build
```
N/A
```

## Other ROM's you maintain officially or unofficially
```
Spark Os Unofficial 
```

## Bugs on unofficial build
```
Notification pannel glitch 
```

## How long have you been building for?
```
2 years 
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No
```

### Telegram username
```
@dead_af69
```

**Comment by deadaf5** [comment]
??

**Comment by whyredfire** [comment]
Please update your device tree repository links.

**Comment by deadaf5** [comment]
> Please update your device tree repository links.

Sorry for this sir but I accidentally lost my dt. I have only a folked one with my own commits

**Comment by hipexscape** [comment]
> Please update your device tree repository links.

ok sir

**Comment by hipexscape** [comment]
please cheak
