### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by hac4us06** [Spark-Rom/official_devices#131]
## Device you want to apply for
```
PocoM3/Redmi9T(Chime)
```

## Device tree sources

```
https://github.com/hac4us06/device_xiaomi_chime13/tree/spark
https://github.com/hac4us06/kernel_xiaomi_chime
https://gitlab.com/chimeoss/vendor_xiaomi_citrus -b lineage-20 vendor/xiaomi/citrus
https://gitlab.com/chimeoss/vendor_xiaomi_lime -b lineage-20 vendor/xiaomi/lime

```

## Link to the platform where you have released your unofficial build
```
https://t.me/ashcafeupdates
```

## Other ROM's you maintain officially or unofficially
```
I'm Derpfest AOSP official maintainer and I also maintain Evo x and sparks at the moment 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@hac4us
```

**Comment by kssrao13882** [comment]
Sending git clone commands for vendor? See atleast those things while applying man.

**Comment by hac4us06** [comment]
> Sending git clone commands for vendor? See atleast those things while applying man.

Sorry for that

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.

**Comment by hac4us06** [comment]
> Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge. You can apply again in the future whenever you've gained more experience.

It's not I don't have a experience our community always have build a single unified build for both pocoM3 and Redmi9T  but now we have decided to deunify and build separately for both devices and for my trees I had re based my trees

**Comment by hac4us06** [comment]
Can you please re consider it. I had rebased my trees that's why it's like
this
