### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by miwu04** [Spark-Rom/official_devices#132]
## Device you want to apply for
```
venus
```

## Device tree sources

```
https://github.com/miwu04/device_xiaomi_venus/tree/Spark
https://github.com/miwu04/device_xiaomi_sm8350-common/tree/Spark
https://github.com/miwu04/kernel_xiaomi_venus
https://github.com/miwu04/vendor_xiaomi_sm8350-common/tree/Spark
https://github.com/miwu04/vendor_xiaomi_venus
https://gitlab.com/FlowerSea0208/vendor_xiaomi_venus-firmware
https://gitlab.com/Stallix/vendor_xiaomi_venus-miuicamera

```

## Link to the platform where you have released your unofficial build
```
https://t.me/Mi11ROMUpdates/486
https://t.me/Mi11ROMUpdates/447

```

## Other ROM's you maintain officially or unofficially
```
Superior (official)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
half a years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
miwu04
```

**Comment by miwu04** [comment]
Restructuring was performed

**Comment by acex69** [comment]
sir why fork dt

**Comment by whyredfire** [comment]
Hi.
We use SystemUIGoogle now; https://github.com/miwu04/device_xiaomi_sm8350-common/blob/b6db1cce3fc015f55b62020fd547470dce5adbcc/common.mk#L457
This flag is redundant and isn't used by us anymore; miwu04/device_xiaomi_sm8350-common@9e2e0abe95422724a7ad403138fb073d8f69c32f
You can inherit this from vendor/spark itself; https://github.com/miwu04/device_xiaomi_sm8350-common/commit/c4d154c7fb510d6ed3d08ca3b269468181451279#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42R86
This is meaningless without CLO's boost framework; miwu04/device_xiaomi_sm8350-common@bd839cf8aca2ded51a8ce5798af7500508e52f7d

**Comment by miwu04** [comment]
> Hi. We use SystemUIGoogle now; https://github.com/miwu04/device_xiaomi_sm8350-common/blob/b6db1cce3fc015f55b62020fd547470dce5adbcc/common.mk#L457 This flag is redundant and isn't used by us anymore; [miwu04/device_xiaomi_sm8350-common@9e2e0ab](https://github.com/miwu04/device_xiaomi_sm8350-common/commit/9e2e0abe95422724a7ad403138fb073d8f69c32f) You can inherit this from vendor/spark itself; [miwu04/device_xiaomi_sm8350-common@c4d154c#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42R86](https://github.com/miwu04/device_xiaomi_sm8350-common/commit/c4d154c7fb510d6ed3d08ca3b269468181451279#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42R86) This is meaningless without CLO's boost framework; [miwu04/device_xiaomi_sm8350-common@bd839cf](https://github.com/miwu04/device_xiaomi_sm8350-common/commit/bd839cf8aca2ded51a8ce5798af7500508e52f7d)

vendor/spark/device_framework_matrix.xml missing  IHighTouchPollingRate
Other commit were fixed

**Comment by miwu04** [comment]
> > Hi. We use SystemUIGoogle now; https://github.com/miwu04/device_xiaomi_sm8350-common/blob/b6db1cce3fc015f55b62020fd547470dce5adbcc/common.mk#L457 This flag is redundant and isn't used by us anymore; [miwu04/device_xiaomi_sm8350-common@9e2e0ab](https://github.com/miwu04/device_xiaomi_sm8350-common/commit/9e2e0abe95422724a7ad403138fb073d8f69c32f) You can inherit this from vendor/spark itself; [miwu04/device_xiaomi_sm8350-common@c4d154c#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42R86](https://github.com/miwu04/device_xiaomi_sm8350-common/commit/c4d154c7fb510d6ed3d08ca3b269468181451279#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42R86) This is meaningless without CLO's boost framework; [miwu04/device_xiaomi_sm8350-common@bd839cf](https://github.com/miwu04/device_xiaomi_sm8350-common/commit/bd839cf8aca2ded51a8ce5798af7500508e52f7d)
> 
> yes,i can inherit device_framework_matrix.xml from vendor/spark itself, but it missing IHighTouchPollingRate Other commit were fixed

sorry,forgot  to push to repo

**Comment by miwu04** [comment]
> Hi. We use SystemUIGoogle now; https://github.com/miwu04/device_xiaomi_sm8350-common/blob/b6db1cce3fc015f55b62020fd547470dce5adbcc/common.mk#L457 This flag is redundant and isn't used by us anymore; [miwu04/device_xiaomi_sm8350-common@9e2e0ab](https://github.com/miwu04/device_xiaomi_sm8350-common/commit/9e2e0abe95422724a7ad403138fb073d8f69c32f) You can inherit this from vendor/spark itself; [miwu04/device_xiaomi_sm8350-common@c4d154c#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42R86](https://github.com/miwu04/device_xiaomi_sm8350-common/commit/c4d154c7fb510d6ed3d08ca3b269468181451279#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42R86) This is meaningless without CLO's boost framework; [miwu04/device_xiaomi_sm8350-common@bd839cf](https://github.com/miwu04/device_xiaomi_sm8350-common/commit/bd839cf8aca2ded51a8ce5798af7500508e52f7d)

please check again

**Comment by whyredfire** [comment]
Cool, everything else looks fine.
