### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by hipexscape** [Spark-Rom/official_devices#133]
## Device you want to apply for
```
Redmi 9 (lancelot)
```

## Device tree sources

```
https://github.com/acex69/android_xaiomi_lancelot
https://github.com/acex69/mt6768-common
https://github.com/acex69/android_kernel_xiaomi_mt6768-2
https://github.com/acex69/proprietary_vendor_xiaomi_lancelot
https://github.com/acex69/proprietary_vendor_xiaomi_mt6768-common
```

## Link to the platform where you have released your unofficial build
```
https://github.com/acex69/Release-by-astro/releases/tag/a13
```

## Other ROM's you maintain officially or unofficially
```
i was maintaining but due to my exams i left for 3 months
```

## Bugs on unofficial build
```
Not yet reported
```

## How long have you been building for?
```
2 years
```

##
```

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.

**Comment by acex69** [comment]
> Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
> You can apply again in the future whenever you've gained more experience.

Sir what can I do to make it up please sir tell me
