### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RjTangpos** [Spark-Rom/official_devices#134]
## Device you want to apply for
```Realme X2/Rmx1991CN
```

## Device tree sources

```
https://github.com/RjTangpos/Experiment_realme_X2/tree/spark

https://github.com/RjTangpos/kernel_realme_sm6150.git

https://gitlab.com/RjTangpos/vendor_realme_x2.git
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/spark-os-unofficial-a13/
```

## Other ROM's you maintain officially or unofficially
```
Evolution X =>
https://drive.google.com/file/d/1cq_sKpLR7WFht-BtNNE7c3FkFFdOoywF/view?usp=share_link

Project Xtended =>
https://drive.google.com/file/d/1bZxh6CQczQF46axtZXZilHlaFHs8htqQ/view?usp=share_link

Project Elixir =>
https://drive.google.com/file/d/1pd2yiYMF1L2noL0Hl_85soI09ZyKzqzF/view?usp=share_link
```

## Bugs on unofficial build
```
FP on AOD 
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Drake39
```

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
