### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RjTangpos** [Spark-Rom/official_devices#136]
## Device you want to apply for
```Realme X2/Rmx1991CN
```

## Device tree sources

```
https://github.com/RjTangpos/Experiment_realme_X2

https://github.com/RjTangpos/kernel_realme_sm6150.git

https://gitlab.com/RjTangpos/vendor_realme_x2.git
```

## Link to the platform where you have released your unofficial build
```
https://forum.xda-developers.com/t/rom-13-0-unofficial-sparkos-aosp-stable-08-03-2023-realme-x2.4562589/#post-88254527
```

## Other ROM's you maintain officially or unofficially
```

Project Xtended =>
https://drive.google.com/file/d/1bZxh6CQczQF46axtZXZilHlaFHs8htqQ/view?usp=share_link

Project Elixir =>
https://drive.google.com/file/d/1pd2yiYMF1L2noL0Hl_85soI09ZyKzqzF/view?usp=share_link
```

## Bugs on unofficial build
```
None 
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Drake39
```

**Comment by RjTangpos** [comment]
Please review! Want to maintain Spark Os for Realme X2 pls

**Comment by kssrao13882** [comment]
> Please review! Want to maintain Spark Os for Realme X2 pls

Have some patience

**Comment by whyredfire** [comment]
As stated earlier, https://github.com/Spark-Rom/official_devices/issues/134#issuecomment-1457964094.
