### ISSUE TITLE
New maintainer for Realme Monet (RMX2020)

### ISSUE THREAD

**Issue by Koushikdey2003** [Spark-Rom/official_devices#137]
## Device you want to apply for
```
Realme Monet (RMX2020)
```

## Device tree sources

```
https://github.com/Koushikdey2003/device_realme_RMX2020
https://github.com/ArrowOS-Devices/android_kernel_realme_RMX2020
https://github.com/Koushikdey2003/vendor_realme_RMX2020
https://github.com/Koushikdey2003/vendor_realme_RMX2020-ims
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/kousick-android-project/files/ROMs/
```

## Other ROM's you maintain officially or unofficially
```
Evolution X, crDroid, Pixel Experience Unofficially 
```

## Bugs on unofficial build
```
Problem in Gapps Build Need to Remove Some Google Stuffs for Smoothness
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
Koushik Dey
https://t.me/Koushikdey3

**Comment by whyredfire** [comment]
Apologies for super late reply, was really caught up in some other stuff.
Everything looks fine to me, accepted!

**Comment by Koushikdey2003** [comment]
No problem sir ik everyone busy in reallife staff + QPR2 rebase
