### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by chematelegram** [Spark-Rom/official_devices#138]
## Device you want to apply for
```
Xiaomi Mi 9 (Cepheus)
```

## Device tree sources

```
https://github.com/chematelegram/device_xiaomi_cepheus
https://github.com/chematelegram/vendor_xiaomi_cepheus
https://github.com/chematelegram/kernel_xiaomi_cepheus
```

## Link to the platform where you have released your unofficial build
```
https://t.me/tribual_mi9/14563
```

## Other ROM's you maintain officially or unofficially
```
Spark for Zippo, EvolutionX for Zippo and Cepheus, crDroid for Zippo
```

## Bugs on unofficial build
```
VoWiFi doesn't work in flight mode
```

## How long have you been building for?
```
~4 months building Spark for Cepheus
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@chematelegram
```

**Comment by whyredfire** [comment]
Apologies for late reply, was really caught up in some other stuff.
Looks fine, accepted!
