### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by nullptr03** [Spark-Rom/official_devices#142]
## Device you want to apply for
```
Redmi Note 9 (merlinx)
```

## Device tree sources

```
https://github.com/nullptr03/android_device_xiaomi_merlinx / https://github.com/nullptr03/android_device_xiaomi_mt6768-common
https://github.com/nullptr03/android_kernel_xiaomi_mt6768
https://github.com/nullptr03/proprietary_vendor_xiaomi_merlinx
```

## Link to the platform where you have released your unofficial build
```
https://t.me/HelioG85_Unified
```

## Other ROM's you maintain officially or unofficially
```
DerpFest (Unofficial)
```

## Bugs on unofficial build
```
USB Tethering
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@nullptr03
```

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.

In particular, your commit history violates our requirements.
