### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by thepriyanshujangid** [Spark-Rom/official_devices#143]
## Device you want to apply for
```
Poco X5 Pro 
```
Your device name and codename
```
Poco X5 Pro  Redwood
```
## Device tree sources

https://github.com/priyanshujangid-redwood/device_xiaomi_redwood 
https://github.com/priyanshujangid-redwood/vendor_xiaomi_redwood
https://github.com/priyanshujangid-redwood/kernel_xiaomi_redwood

## Link to the platform where you have released your unofficial build
```
https://t.me/sparkOSRedwood/57
```

## Other ROM's you maintain officially or unofficially
```
cherishOS (officially)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
thepriyanshujangid
```

**Comment by kartik-commits** [comment]
> ## Device you want to apply for
> 
> ```
> Poco X5 Pro 
> ```
> 
> Your device name and codename
> 
> ```
> Poco X5 Pro  Redwood
> ```
> 
> ## Device tree sources
> 
> ```
> https://github.com/priyanshujangid-redwood/device_xiaomi_redwood 
> https://github.com/priyanshujangid-redwood/vendor_xiaomi_redwood
> https://github.com/priyanshujangid-redwood/kernel_xiaomi_redwood
> ```
> 
> ## Link to the platform where you have released your unofficial build
> 
> ```
> https://t.me/poco_x5_pro_roms/20600
> ```
> 
> ## Other ROM's you maintain officially or unofficially
> 
> ```
> cherishOS (officially)
> ```
> 
> ## Bugs on unofficial build
> 
> ```
> None
> ```
> 
> ## How long have you been building for?
> 
> ```
> Months
> ```
> 
> ## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
> 
> ```
> I read everything properly and I violate none of the requirements.
> ```
> 
> ## SELinux status?
> 
> ```
> Enforcing.
> ```
> 
> ## Are you using a prebuilt kernel? If yes, why?
> 
> ```
> No.
> ```
> 
> ## Contact
> ### Telegram username
> 
> ```
> thepriyanshujangid
> ```

Wow, Finally SparkOS official soon. Been waiting for 3 months since bought redwood.

**Comment by whyredfire** [comment]
NO, you've literally repicked the whole tree again for no reason.
This isn't acceptable at all.

**Comment by thepriyanshujangid** [comment]
can you  explain  me  more 
repicked whole tree ??

**Comment by thepriyanshujangid** [comment]
> NO, you've literally repicked the whole tree again for no reason. This isn't acceptable at all.

can you explain me more
repicked whole tree ??
i did  rebase   my  tree
