### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by chuspita** [Spark-Rom/official_devices#148]
## Device you want to apply for
Poco X5 Pro 5G
Your device name and codename
Redwood

## Device tree sources

```
https://github.com/chuspita/device_xiaomi_redwood
https://github.com/chuspita/kernel_xiaomi_redwood
https://github.com/chuspita/vendor_xiaomi_redwood
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/spark-redwood/files/
```

## Other ROM's you maintain officially or unofficially
```
Aphadroid, Bananadroid
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Three years ago
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
chuspita
Your Telegram username
@franlop77

**Comment by whyredfire** [comment]
Hi, you're supposed write commit message headers in a similar fashion. I see a lot of commits with sm8350-common,  sm7325-common and even lisa, rebase and change all of them to redwood.
This is not required, https://github.com/chuspita/device_xiaomi_redwood/commit/e18f7ce294855afca9b308c94575994e93bf911a.
This is a very bad practice, please drop https://github.com/chuspita/device_xiaomi_redwood/commit/3a2dae3fb465e023779698904c7471bfa86b5577.
Update this from stock https://github.com/chuspita/device_xiaomi_redwood/blob/f4a8c83209f72dd17ac77db394b9826d7181cae0/BoardConfig.mk#L188.
You might want to pick this too as livedisplay doesn't seem to work on my sm8350 devices, you can check on yours before you drop it, https://github.com/PixelOS-Devices/device_xiaomi_lisa/commit/9eeef97cd6003fd62a31e17c4231361366665a3f.

Other than that, I see you've imported powerhint json, but you haven't switched to libperf at all. I'll link my device tree here for reference which might help you with this, https://github.com/PixelOS-Devices/device_xiaomi_lisa/commits/70fd280c135a9f563a13d065ff0956fcaf6e9a3b (commits starting from Drop qti perfd stack till head, you can ignore powerhint changes and can keep yours if you like),

I'll keep this application on hold for a week.

**Comment by chuspita** [comment]
I have already made some changes in DT!....Thank You

**Comment by chuspita** [comment]
Any problem?

**Comment by whyredfire** [comment]
Hi, you're supposed write commit message headers in a similar fashion. I see a lot of commits with sm8350-common, sm7325-common and even lisa, rebase and change all of them to redwood.
Kindly rebase it.

**Comment by chuspita** [comment]
Changes made. I think I've done everything you asked of me. Now, if you want, I will be the maintainer of Spark for enchanted Redwood, but I will not modify my DTs anymore because they are very stable. I offer seriousness and support.
Thanks and greetings!

**Comment by whyredfire** [comment]
Looks good, two more things remaining.
https://github.com/chuspita/device_xiaomi_redwood/commit/21452b8287bfead75c2b27f44c4def5643f1dfa8, this doesn't do anything at all, infact the thing doesn't exist anymore.
Disable livedisplay with overlay as mentioned in the first comment as it doesn't work properly, resets on turning off display for xiaomi lahaina devices atleast.

Once you're done with them, pm spkal on telegram, we're good to go.
