### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ramshell688** [Spark-Rom/official_devices#149]
## Device you want to apply for
```
Poco M3 Pro/Redmi Note 10T/10 5G/11 SE (camellia)
```

## Device tree sources
```
https://github.com/ramshell688/device_xiaomi_camellia
https://github.com/ramshell688/kernel_xiaomi_camellia
https://github.com/ramshell688/vendor_xiaomi_camellia
```

## Link to the platform where you have released your unofficial build
```
https://t.me/ramsprojects/194
```

## Other ROM's you maintain officially or unofficially
```
CherishOS Official & PixelExtended Official, and some unofficial roms
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
4 month ago
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes, mediatek kernel not open source
```

### Telegram username
```
@ramshell688
```

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
