### ISSUE TITLE
New maintainer for Realme 8 [Nashc]

### ISSUE THREAD

**Issue by venudinesh** [Spark-Rom/official_devices#150]
## Device you want to apply for
```
Realme 8 [Nashc]
```

## Device tree sources

```
https://github.com/venudinesh/android_device_realme_nashc
https://github.com/venudinesh/kernel_realme_nashc
https://github.com/venudinesh/vendor_realme_nashc
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Realme8AOSP/20
```

## Other ROM's you maintain officially or unofficially
```
Cherish OS official
Unofficial - spark, alphadroid
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 year
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### https://t.me/sukuna_me
```
sukuna_me
```

**Comment by whyredfire** [comment]
Hello.
Drop https://github.com/venudinesh/android_device_realme_nashc/commit/114ae1c158a85453be954969f802d5ef9f96cd85 and https://github.com/venudinesh/android_device_realme_nashc/commit/a312b5a8cf700c29e1347234658f33862585c1f2, inherit fcm from `vendor/spark/config/device_framework_matrix.xml`.
Write your commit titles in a similar fashion, with `nashc: Message goes here`.

I'll put your application on hold for a week for now till you fix it.

**Comment by venudinesh** [comment]
hello sir,
i have done everything
please check the tree again
thank you for responding.

**Comment by whyredfire** [comment]
I don't see an year of building experience on your GitHub account.

![image](https://github.com/Spark-Rom/official_devices/assets/72072109/0867790e-d8fb-43ba-8341-e14199ad94e9)

...

**Comment by venudinesh** [comment]
I got an 8 months of experience of building roms
I have built so many unofficial roms and official maintainer for ancient
and cherish. I rebase my trees and upload new sometimes so they look like
new
That's why those look like weeks old
Thank you
