### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by SharmagRit** [Spark-Rom/official_devices#151]
## Device you want to apply for
```
Poco F5 aka marble
```

## Device tree sources

```
https://github.com/SharmagRit/android_device_xiaomi_marble

https://github.com/SharmagRit/android_vendor_xiaomi_marble

https://github.com/SharmagRit/android_device_xiaomi_marble-kernel
```

## Link to the platform where you have released your unofficial build
```
@marble_builds
```

## Other ROM's you maintain officially or unofficially
```
RisingOS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Approx 4 years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
SharmagRit
```

**Comment by whyredfire** [comment]
We discourage resetting and repicking commits without any changes.
