### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Drpto** [Spark-Rom/official_devices#153]
## Device you want to apply for
```
Redmi Note 12 5G/Poco x5 5G (stone)
```

## Device tree sources

```
https://github.com/Drpto/device_xiaomi_stone -b spark
https://github.com/Drpto/device_xiaomi_sm6375-common -b spark
https://github.com/Stone-Trees/device_xiaomi_stone-kernel

```

## Link to the platform where you have released your unofficial build
```
https://t.me/moonstone_updates/69
```

## Other ROM's you maintain officially or unofficially
```
Yes, AlphaDroid & DroidX-UI Officially for violet device.
```

## Bugs on unofficial build
```
Fm Radio crashing
```

## How long have you been building for?
```
1 Year
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes, Due to lack of devlopers.
```

### Telegram username
```
Dr_Opto
```

**Comment by whyredfire** [comment]
- This isn't a thing anymore, you can drop it. https://github.com/Drpto/device_xiaomi_sm6375-common/commit/4a78f2c1dce472af99b66aa17627b69fd65e1e68.
- This works only with CLO's boostframework, useless for us on AOSP roms. https://github.com/Drpto/device_xiaomi_sm6375-common/commit/6568b4753b9073c37165b13dd4fe50263f80f9e2
- These shouldn't be set in the device tree, https://github.com/Drpto/device_xiaomi_sm6375-common/commit/51d708c19237465ad42be0e8360727ef3f3023f5.
- If you're importing this in the device tree itself, https://github.com/Drpto/device_xiaomi_sm6375-common/commit/b2f7d576282136a2dc775904510ca44d76d1e7e8, drop it from vendor tree, https://github.com/Drpto/device_xiaomi_sm6375-common/blob/2b54afca0175326362e5907019dd29ef602d72e6/proprietary-files.txt#L379.

I'll put this application on hold while you fix these issues.

**Comment by Drpto** [comment]
I fixes all the charges, which you are mentioned. Please check it.

**Comment by Drpto** [comment]
Please check it.. i will done all the changes which you are mentioned.

**Comment by Drpto** [comment]
Please check that. All gixed
