### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by vherawidatama** [Spark-Rom/official_devices#154]
## Device you want to apply for
```
Redmi Note 12 Turbo / Poco F5 (marble)
```

## Device tree sources

```
https://github.com/marble-indonesia/device_xiaomi_marble.git
https://github.com/marble-indonesia/vendor_xiaomi_marble.git
https://github.com/marble-indonesia/device_xiaomi_marble-kernel.git
https://github.com/marble-indonesia/hardware_xiaomi.git
```

## Link to the platform where you have released your unofficial build
```
https://t.me/SMGLaboratoryCH/335
```

## Other ROM's you maintain officially or unofficially
```
CherishOS unofficial
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 Years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
SMGLaboratory
```

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.

In particular, your commit history violates our requirements.
