### ISSUE TITLE
Re applied for new maintainer, with the fixes which is told in previous application 

### ISSUE THREAD

**Issue by Drpto** [Spark-Rom/official_devices#155]
## Device you want to apply for
```
Redmi Note 12 5G/Poco x5 5G (stone)
```

## Device tree sources

```
https://github.com/Drpto/device_xiaomi_stone -b spark
https://github.com/Drpto/device_xiaomi_sm6375-common -b spark
https://github.com/Stone-Trees/device_xiaomi_stone-kernel

```

## Link to the platform where you have released your unofficial build
```
https://t.me/moonstone_updates/69
```

## Other ROM's you maintain officially or unofficially
```
Yes, AlphaDroid & DroidX-UI Officially for violet device.
```

## Bugs on unofficial build
```
Fm Radio crashing
```

## How long have you been building for?
```
1 Year
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes, Due to lack of devlopers.
```

### Telegram username
```
Dr_Opto
```

**Comment by whyredfire** [comment]
Looks good, just rebase your device specific tree a bit.
Reset till 9b316154d238edfffd6f0e0a5648a42a29bfe62a, and pick back the top two commits.

I just looked back at your previous application, it didn't appear on open issues as you yourself marked it as close.
Regardless, all good now ;)
