### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by redcliff-op** [Spark-Rom/official_devices#38]
**Device and Codename**
Device - Poco X2 ( Redmi K30 )
Codename - Phoenix

**Sources**
Kernel Tree - https://github.com/redcliff-op/android_kernel_xiaomi_phoenix.git
Device Tree - https://github.com/redcliff-op/device_xiaomi_phoenix.git
Vendor Tree - https://github.com/redcliff-op/vendor_xiaomi_phoenix.git

**Other ROM's I maintain**
Octavi
DerpFest

**Bugs on unofficial build**
None

**How long have I been building for?**
10+ Months

**SELinux status**
Enforcing.

I read everything properly and I violate none of the requirements.

**Contact**
Telegram - https://t.me/RedcliffOP

**Comment by spkal01** [comment]
Everything seems fine and up 2 the requirements !
