### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by tioburla** [Spark-Rom/official_devices#39]
## Device you want to apply for
'Redmi 4X'
Your device name and codename
`Redmi 4X(SANTONI)`

## Device tree sources

```
https://github.com/tioburla/android_device_xiaomi_santoni
https://github.com/tioburla/project_kernel_WolfKernel
https://github.com/tioburla/android_vendor_xiaomi_santoni
## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
Insert here
BlissROM

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Weeks/Months/Years
3Years

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
Yes

## SELinux status?
```
Permissiver
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
https://t.me/tioburla
Your Telegram username
TioBurla

**Comment by spkal01** [comment]
Your trees aren't adapted to spark I can only see a bliss branch

**Comment by spkal01** [comment]
24 hours have passed no progress has be done I'm closing the issue. You can  re open one once you adress all the issues mentioned above
