### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by ghost** [Spark-Rom/official_devices#40]
## Device you want to apply for
```
Redmi Note 7/7s ( Lavender )
```

## Device tree sources

```
https://github.com/inferno964/spark_device_xiaomi_lavender
https://github.com/inferno964/device_xiaomi_sdm660-common
https://github.com/inferno964/vendor_xiaomi_lavender
https://github.com/inferno964/vendor_xiaomi_sdm660-common
https://github.com/inferno964/kernel_xiaomi_lavender
```

## Link to the platform where you have released your unofficial build
```
https://drive.google.com/uc?id=1R8FOmyPEE8rZcIjdtQm-ay49z14hCitb&export=download
```

## Other ROM's you maintain officially or unofficially
```
Unofficial - Pixel Experience 12 , Styx Project
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Nearly 2 months 
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@inferno964
```

**Comment by ghost** [comment]
Update dt source link.

**Comment by spkal01** [comment]
Everything looks good 
Status: Accepted
