### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by tusharind007** [Spark-Rom/official_devices#41]
## Device you want to apply for
```
Redmi Note 9 Pro/Pro Max/9S/10 Lite/ POCO M2 Pro (miatoll)
```

## Device tree sources

```
https://github.com/tusharind007/device_xiaomi_miatoll
https://github.com/tusharind007/device_xiaomi_sm6250-common
https://github.com/tusharind007/kernel_xiaomi_sm6250
https://github.com/tusharind007/vendor_xiaomi_sm6250-common
https://github.com/tusharind007/vendor_xiaomi_miatoll
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
project elixir,AOSPK
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 Years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Tusharind007
```

**Comment by spkal01** [comment]
Everything looks good 
Status: Accepted
