### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Krxyzn** [Spark-Rom/official_devices#43]
## Device you want to apply for
```
Redmi 4X | Santoni
```

## Device tree sources

```
https://github.com/JktFdrxProjektz/device_xiaomi_santoni
https://github.com/mi-msm8937/android_kernel_xiaomi_msm8937
https://github.com/JktFdrxProjektz/vendor-santoni-1
```

## Link to the platform where you have released your unofficial build
```
Missing link :(
```

## Other ROM's you maintain officially or unofficially
```
OFFICIAL: AncientOS, Kasumi Project, KomodoOS
```

## Bugs on unofficial build
```
• FPC doesn't work on encrypted device
```

## How long have you been building for?
```
5 Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Krxyzn
```

**Comment by spkal01** [comment]
1 Your tree isn't adapted to spark 
2 What does fpc stand for ?

**Comment by spkal01** [comment]
Sorry you aren't accepted mate as your tree doesn't have a satisfying bring up commit. More specifically you have 3 commits that should have been rebased + you don't have much history or progress on the tree. If you want you can re apply after fixing the above issues. Good luck
