### ISSUE TITLE
New maintainer - Xiaomi POCO F1

### ISSUE THREAD

**Issue by resist15** [Spark-Rom/official_devices#44]
## Device you want to apply for
```
Xiaomi POCO F1 - beryllium
```

## Device tree sources

```
https://github.com/resist15/device_xiaomi_beryllium
https://github.com/resist15/device_xiaomi_sdm845-common
https://github.com/PainKiller3/kernel_xiaomi_sdm845/tree/twelve
https://github.com/resist15/vendor_xiaomi
```
## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
8 Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@resist15
```

**Comment by spkal01** [comment]
Everything looks fine.

Status: Accepted
