### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by mrfox2003** [Spark-Rom/official_devices#45]
## Device you want to apply for
```
Redmi Note 7 Pro (Violet)
```

## Device tree sources

```
https://github.com/mrfox2003/S_device_xiaomi_violet.git
https://github.com/karthik558/MsM-4.14-RyZeN-.git
https://github.com/mrfox2003/vendor_xiaomi_violet.git
```

## Link to the platform where you have released your unofficial build
```
https://t.me/violetofficialupdates/4463
```

## Other ROM's you maintain officially or unofficially
```
Voltage OS, Bananadroid
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
5 months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes , inline kernel are laggy
```

### Telegram username
```
@mrfox2003
```

**Comment by spkal01** [comment]
Everything looks fine Status: Accepted
