### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RsydAl587** [Spark-Rom/official_devices#46]
## Device you want to apply for
```
Redmi Note 4 (mido)
...

## Device tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```
https://github.com/RasyidAlKautsar/android_device_xiaomi_mido
https://github.com/RasyidAlKautsar/kernel_mido
https://github.com/Redmi-note-4x/proprietary_vendor_xiaomi
```

## Link to the platform where you have released your unofficial build
```
https://t.me/mido_universal/13005
```

## Other ROM's you maintain officially or unofficially
```
NusantaraProject, Project-Awaken, CherishOS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
### Telegram username
```
@AswLueEmang
```

**Comment by spkal01** [comment]
Hello thanks for applying everything device side looks good but we only accept people who maintain along with spark 3 roms in total

**Comment by RsydAl587** [comment]
ok, sir
I dropped Nusantara Project Unofficial because A11

**Comment by spkal01** [comment]
Oke so 2 last things and you are accepted 
1 https://github.com/RasyidAlKautsar/android_device_xiaomi_mido/commit/e4a59e74268076802145bba06fb32fc47f819145 

Drop this commit as we include graphene camera by default
2 https://github.com/RasyidAlKautsar/android_device_xiaomi_mido/blob/50c5b25c31f438d8ec57dac05986912b481bc47e/system.prop
 Create a support group if you haven't already and put the link here

**Comment by RsydAl587** [comment]
ok, sir

**Comment by RsydAl587** [comment]
https://github.com/RasyidAlKautsar/android_device_xiaomi_mido/commits/Spark-12
Correct, sir?

**Comment by spkal01** [comment]
Yes
Status: Accepted
