### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Vitorgl2003** [Spark-Rom/official_devices#47]
## Device you want to apply for
```
Redmi Note 7/7s ( Lavender )
```

## Device tree sources

```
https://github.com/Vitorgl2003/device_xiaomi_lavender_2
https://github.com/Vitorgl2003/kernel_xiaomi_lavender
https://github.com/Vitorgl2003/android_vendor_xiaomi_lavender
```

## Link to the platform where you have released your unofficial build
```
https://mega.nz/file/Zw9wxQga#G5QoRAnDiy8fvXdQhe0Q2nMNa3koabYpa7bPp8UiOEM
```

## Other ROM's you maintain officially or unofficially
```
Unofficial - Awaken and AEX 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 months and 3 weeks
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@bitortheaddicted
```

**Comment by spkal01** [comment]
Seems good 
Status: Accepted
