### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by Faisalhossainerfan** [Spark-Rom/official_devices#49]
## Device you want to apply for
```
Redmi 4/4X santoni

```

## Device tree sources

```
https://github.com/Faisalhossainerfan/device_xiaomi_santoni
https://github.com/Jabiyeff/vendor-santoni
https://github.com/Jabiyeff/msm-4.9-santoni-kud
```

## Link to the platform where you have released your unofficial build
```
https://t.me/r4xchannel/4798
```

## Other ROM's you maintain officially or unofficially
```
Pixel experience
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@faisalhossainerfan
```

**Comment by spkal01** [comment]
Hey you need to address some things 
1 Answer with a valid time amount at the question "how long have you been building for"
2 your sparkify commit is a bit messy maybe split it up

**Comment by Faisalhossainerfan** [comment]
> Hey you need to address some things 1 Answer with a valid time amount at the question "how long have you been building for" 2 your sparkify commit is a bit messy maybe split it up

Sir question 2 i don’t understand what messy. did you mean split cleanups in 2/3 commits?

**Comment by spkal01** [comment]
Status: Rejected no contributions on dt  + invalid building time answer on form.
