### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by mrtechnostart** [Spark-Rom/official_devices#50]
## Device you want to apply for
```
Redmi 7/Y3 Onclite
```

## Device tree sources

```
https://github.com/TechnoStartOfficial/device_xiaomi_onclite_spark.git
https://github.com/TechnoStartOfficial/android_kernel_xiaomi_onclite.git
https://github.com/TechnoStartOfficial/vendor_xiaomi_onclite.git
```

## Link to the platform where you have released your unofficial build
```
https://t.me/oncliteupdates/390
```

## Other ROM's you maintain officially or unofficially
```
Raven OS Official
Xtended Official

```

## Bugs on unofficial build
```
Recovery Struck Issue (FIXED NOW) edited
No Issues Reported Till Now
Review Of UnOfficial Build: https://www.youtube.com/watch?v=baWYMFUCS_Y
```

## How long have you been building for?
```
2 Week
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@MrTechnoStart
```

**Comment by mrtechnostart** [comment]
Sir Waiting For Your Reply

**Comment by spkal01** [comment]
Keep waiting

**Comment by mrtechnostart** [comment]
Ohk

**Comment by mrtechnostart** [comment]
Waiting Sir

**Comment by spkal01** [comment]
Hwvw you been making roms in total for 2 weeks ?

**Comment by mrtechnostart** [comment]
Hello Sir, Me Started Learning From 18 Jan 2022

**Comment by mrtechnostart** [comment]
But my git skills are 6+/10 and i am learning daily, you can check that from my contributions on my github profile

**Comment by spkal01** [comment]
Status Accepted
