### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by th4rv4** [Spark-Rom/official_devices#51]
## Device you want to apply for
```
Realme 6,6i(Indian),6s,7,Narzo 20 Pro,Narzo 30 4G (**RM6785 Unified**)
```

## Device tree sources

```
https://github.com/Atharva-Agnihotri7115/android_device_realme_RM6785/tree/12
https://github.com/sarthakroy2002/kernel_realme_wasabi
https://github.com/Atharva-Agnihotri7115/proprietary_vendor_realme
```

## Link to the platform where you have released your unofficial build
```
https://t.me/realme7updater/211
```

## Other ROM's you maintain officially or unofficially
```
Unofficially:-Evo-X & Pixel Etended
```

## Bugs on unofficial build
```
In Built Screen Recorder
```

## How long have you been building for?
```
6Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Permissive
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Atharva_Agnihotri
```

**Comment by spkal01** [comment]
Looks good . Only bummer is that the build is Permissive. Any reason why its not enforcing ?

**Comment by th4rv4** [comment]
Actually It's Been Only A Month Or So Since We Have Unified Our Sources And Did A Complete A12 Bringup....So It is at its early stage that's y it's Permissive for now.

**Comment by spkal01** [comment]
Status: Accepted
