### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by XBIZART** [Spark-Rom/official_devices#52]
## Device you want to apply for
```
REDMI NOTE 9 (MERLINX)
```

## Device tree sources

```
https://github.com/XBIZART/android_device_xiaomi_merlinx_spark
https://github.com/XZI-TEAM4646/Violet-Kernel
https://github.com/XBIZART/android_vendor_xiaomi_merlinx
https://github.com/XBIZART/android_device_xiaomi_mt6768-common
https://github.com/rubyzee/device_mediatek_sepolicy_vndr
```

## Link to the platform where you have released your unofficial build
```
[Insert here](https://t.me/XZIUPDATE/610)
```

## Other ROM's you maintain officially or unofficially
```
[Insert here](https://t.me/XZIUPDATE/563) https://t.me/XZIUPDATE/642
```

## Bugs on unofficial build
```
Encrypted
```

## How long have you been building for?
```
1,2 years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@XBIZART
```

**Comment by spkal01** [comment]
Everything looks good only issues I have with your form is the amount of roms you maintain. We only accept people who maintain max 3 roms along with spark

**Comment by spkal01** [comment]
This issue will be closed automatically on 24h cause of inactivity
