### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by MudabbirulSaad** [Spark-Rom/official_devices#53]
## Device you want to apply for
```
Realme 5, 5i, 5s (r5x)
```

## Device tree sources

```
https://github.com/MudabbirulSaad/device_realme_r5x
https://github.com/MudabbirulSaad/kernel_realme_r5x
https://github.com/MudabbirulSaad/vendor_realme_r5x
```

## Link to the platform where you have released your unofficial build
```
Vanilla: https://we.tl/t-ivf2uubWX7
Gapps: https://we.tl/t-MBn1SImGiQ
```

## Other ROM's you maintain officially or unofficially
```
Nothing right now.
```

## Bugs on unofficial build
```
Didn't find major bug except systemUI reboot
```

## How long have you been building for?
```
2 weeks
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
MudabbirulSaad
```

**Comment by spkal01** [comment]
Status Declined

Reason: 0 contributions + tree not adapted to spark + insufficient experience

**Comment by MudabbirulSaad** [comment]
@spkal01 sir my current build with trees is showing some major bugs which I never faced with other roms and I'm trying to fix with my best. So, can I reapply later?

**Comment by spkal01** [comment]
Sure just make sure your trees are up to the standards

**Comment by MudabbirulSaad** [comment]
Thank you !
