### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by resist15** [Spark-Rom/official_devices#54]
## Device you want to apply for
```
Xiaomi Poku F1
```
## Device tree sources

```
https://github.com/resist15/android_device_xiaomi_beryllium/tree/12.1
https://github.com/resist15/android_kernel_xiaomi_sdm845
https://github.com/resist15/android_vendor_xiaomi
https://github.com/resist15/android_device_xiaomi_sdm845-common
```

## Link to the platform where you have released your unofficial build
```
telegram
```

## Other ROM's you maintain officially or unofficially
```
cipher and ded radiant
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
in next month 1 year
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@xyz_sourav
```

**Comment by spkal01** [comment]
Pobg phone going official long live Poco # I love Poco # I will die for Poco
