### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by anandhan07** [Spark-Rom/official_devices#55]
## Device you want to apply for
```
Redmi 5 Plus / Vince
```

## Device tree sources

```
https://github.com/anandhan07/android_device_xiaomi_vince
https://github.com/GhostMaster69-dev/android_kernel_xiaomi_vince
https://github.com/anandhan07/android_vendor_xiaomi_vince
```

## Link to the platform where you have released your unofficial build
```
https://t.me/anandhansprjkts/282
```

## Other ROM's you maintain officially or unofficially
```
was maintained Project Sakura-A11 (Unofficial), No other official till now.
```

## Bugs on unofficial build
```
Data on sim 2 (on last unofficial build). But fixed now.
```

## How long have you been building for?
```
10 Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@anandhan077
```

**Comment by spkal01** [comment]
Everything looks good. Status: Accepted
