### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RahulGorai0206** [Spark-Rom/official_devices#59]
## Device you want to apply for
```
POCO F1 / Beryllium
```

## Device tree sources

```
https://github.com/RahulGorai0206/device_xiaomi_beryllium
https://github.com/RahulGorai0206/kernel_xiaomi_sdm845
https://github.com/RahulGorai0206/vendor_xiaomi
```

## Link to the platform where you have released your unofficial build
```
https://t.me/PocoPhoneGlobalUpdates/7099
```

## Other ROM's you maintain officially or unofficially
```
None
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
4 Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@RahulGorai
```

**Comment by spkal01** [comment]
Everything looks good Status: Accepted
