### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by killcmd** [Spark-Rom/official_devices#60]
## Device you want to apply for
```
OnePlus 8 instantnoodle
```

## Device tree sources

```
https://github.com/killcmd/kernel_onplus_sm8250
https://gitlab.com/killcmd/ramen
https://gitlab.com/killcmd/vendor_oneplus
```

## Link to the platform where you have released your unofficial build
```
https://forum.xda-developers.com/t/rom-12-1-unofficial-spark-os-v12-2-instantnoodle.4429449
```

## Other ROM's you maintain officially or unofficially
```
ArrowOS-Unofficial
AOSPExtended-Unofficial
```

## Bugs on unofficial build
```
None other than UI issues found on Android. 
```

## How long have you been building for?
```
Since the Galaxy S4. 
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/i_used_to_be_cool
```

**Comment by spkal01** [comment]
Hey plz update your commit naming in order for them to be more descriptive thanks

**Comment by killcmd** [comment]
Sure bud

**Comment by killcmd** [comment]
Updated the commits to what I remembered, not the most detailed but it's actually an idea of what happened.

**Comment by spkal01** [comment]
https://gitlab.com/killcmd/ramen/-/commit/82c85f042a495af294d7da61968892836fed141c

https://gitlab.com/killcmd/ramen/-/commit/a90179a10cd48ea53352ea64a9cb916bde4ceaf9

Drop those commits also are you the author of the whole tree ?

**Comment by killcmd** [comment]
Unfortunately I am. I'll drop those commits later on today.

**Comment by spkal01** [comment]
Hey everything is fine just a question why do you use gitlab for the dt any specific reason ?

**Comment by killcmd** [comment]
Github made me enable LFS on a few uploads I did a while back for my ArrowOS DT and Common, which bugged me a little. It's more a preference not an essential need,

**Comment by spkal01** [comment]
Status Accepted but plz ammend your dt commits for  more descriptive commit naming

**Comment by killcmd** [comment]
Ok
