### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RahulGorai0206** [Spark-Rom/official_devices#61]
## Device you want to apply for
```
Redmi Note 8 / Ginkgo
```

## Device tree sources

```
https://github.com/RahulGorai0206/device_xiaomi_ginkgo
https://github.com/RahulGorai0206/kernel_xiaomi_ginkgo
https://github.com/RahulGorai0206/vendor_xiaomi_ginkgo
```

## Link to the platform where you have released your unofficial build
```
https://t.me/rn8updates/6489
```

## Other ROM's you maintain officially or unofficially
```
No
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
3 Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@RahulGorai
```

**Comment by spkal01** [comment]
Drop this https://github.com/RahulGorai0206/device_xiaomi_ginkgo/commit/461d3c2e7826bcaccf656bd98534c059388494ed

Rebase this https://github.com/RahulGorai0206/device_xiaomi_ginkgo/commit/614628bf9c1b786e6972a0832de20bd4d3bc6331

**Comment by RahulGorai0206** [comment]
Ok

**Comment by RahulGorai0206** [comment]
> Drop this [RahulGorai0206/device_xiaomi_ginkgo@461d3c2](https://github.com/RahulGorai0206/device_xiaomi_ginkgo/commit/461d3c2e7826bcaccf656bd98534c059388494ed)
> 
> Rebase this [RahulGorai0206/device_xiaomi_ginkgo@614628b](https://github.com/RahulGorai0206/device_xiaomi_ginkgo/commit/614628bf9c1b786e6972a0832de20bd4d3bc6331)

fixed sir

**Comment by spkal01** [comment]
Status: Accepted
