### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by pranshoe** [Spark-Rom/official_devices#62]
## Device you want to apply for
```
Redmi Note 5 Pro(whyred)
```

## Device tree sources

```
https://github.com/datnerdguy/device_xiaomi_whyred
https://github.com/pzqqt/android_kernel_xiaomi_whyred-4.19
https://github.com/datnerdguy/vendor_xiaomi_whyred
```

## Link to the platform where you have released your unofficial build
```
I havent released my build yet but will do it soon
https://drive.datnerdguy.workers.dev/0:/ROMs%20by%20me/Spark-12.2-UNOFFICIAL-whyred-20220423-gapps.zip
```

## Other ROM's you maintain officially or unofficially
```
I have built four roms unofficially till now:
CipherOS
HavocOS
POSP
DotOS
```

## Bugs on unofficial build
```
None as of now
```

## How long have you been building for?
```
1 month
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I have read everything properly and do not violate any thing.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@datnerdguy
```

**Comment by spkal01** [comment]
Hey you have built a one time build for these roms or you maintain them ?

**Comment by pranshoe** [comment]
I have made a one time build but am looking forward to maintain Dot officially and POSP unofficially.

**Comment by spkal01** [comment]
Hey have you released your build on any platform ? Also you need to drop some roms cause we allow only 3 roms in total along with spark

**Comment by pranshoe** [comment]
Yes I have released my builds on https://www.pling.com/p/1742369/ but will release my Spark build soon (altho I have given 3-4 people access to it).
As far as maintaining only 3 roms, I can drop POSP.

**Comment by pranshoe** [comment]
Released :D

**Comment by spkal01** [comment]
Send a link to the post ;)

**Comment by pranshoe** [comment]
https://t.me/whyredupdates/12724

**Comment by spkal01** [comment]
Status: Accepted but make sure you drop one of the roms
