### ISSUE TITLE
New maintainer for Xiaomi Mi A1 (tissot)

### ISSUE THREAD

**Issue by MetoisTaken** [Spark-Rom/official_devices#63]
## Device you want to apply for
```
Xiaomi Mi A1 (tissot)
```

## Device tree sources

```
https://github.com/MetoIsTaken/device_xiaomi_tissot
https://github.com/MetoIsTaken/device_xiaomi_msm8953-common
https://github.com/MetoIsTaken/kernel_xiaomi_tissot
https://github.com/MetoIsTaken/vendor_xiaomi_tissot // used pixel repos its private now
https://github.com/MetoIsTaken/vendor_xiaomi_msm8953-common // used pixel repos its private now
```

## Link to the platform where you have released your unofficial build
```
https://forum.xda-developers.com/t/rom-12-1-tissot-unofficial-spark-os-12-2-22-04-22.4435561/
@tissot_sprout telegram channel
```

## Other ROM's you maintain officially or unofficially
```
CorvusOS Unofficial
CherishOS -> Unofficial(not released)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 Weeks. 1 week for sure about stability. 1 week release.
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@MetoIsTaken
```

**Comment by spkal01** [comment]
Your main dt isn't adapted to spark
