### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by mrfox2003** [Spark-Rom/official_devices#68]
## Device you want to apply for
```
Redmi Note 10 Pro (sweet)
```

## Device tree sources

```
https://github.com/mrfox2003/device_xiaomi_sweet_oss
https://github.com/shashank1439/kernel_xiaomi_sweet.git
https://github.com/mrfox2003/vendor_xiaomi_sweet.git
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
Awaken
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 Year
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@mrfox2003
```

**Comment by spkal01** [comment]
Where unofficial build ?

**Comment by mrfox2003** [comment]
> Where unofficial build ?

https://t.me/RedmiNote10ProChannel/1088

**Comment by spkal01** [comment]
Why have you picked even the initial commit of the tree ? Instead of rebasing onto it
