### ISSUE TITLE
New maintainer for Redmi 8A Dual

### ISSUE THREAD

**Issue by ghost** [Spark-Rom/official_devices#71]
## Device you want to apply for

Redmi 8A Dual olivewood

## Device tree sources

https://github.com/JaswalAshish/device_xiaomi_olivewood.git
https://github.com/JaswalAshish/kernel_xiaomi_olivewood.git
https://github.com/JaswalAshish/vendor_xiaomi_olivewood.git

## Link to the platform where you have released your unofficial build

https://t.me/Redmi8AOfficial/277885

## Other ROM's you maintain officially or unofficially

Evolution X And ProjectElixir as official

## Bugs on unofficial build

None

## How long have you been building for?

9 Months

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?

I read everything properly and I violate none of the requirements.

## SELinux status?

Enforcing.

## Are you using a prebuilt kernel? If yes, why?

No.

### Telegram username

@jaswal_ashish

**Comment by spkal01** [comment]
Status: Accepted
