### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Pyrtle93** [Spark-Rom/official_devices#74]
## Device you want to apply for
```
Your device name and codename
``` OnePlus 8t/9r (lemonkebab)

## Device tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```
https://github.com/Pyrtle93/device_oneplus_lemonkebab/tree/spark
https://github.com/Pyrtle93/IllusionX_sm8250
https://github.com/Pyrtle93/vendor_oneplus_lemonkebab
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Derp8t
```

## Other ROM's you maintain officially or unofficially
```
I was maintaining derpfest for this device for about a year but now I'm not
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
3 almost 4 years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
### Telegram username
```
Your Telegram username
```
@APyrtle93

**Comment by spkal01** [comment]
Hey plz split this commit to 2 parts 1 for the sparkify rebrand and another for whatever changes you have done on parts https://github.com/Pyrtle93/device_oneplus_lemonkebab/commit/b2092e07a1314b12970b4b837cdf39901b1df5c9

**Comment by Pyrtle93** [comment]
I just squashed reverts into the spark-ify commit. Can I just add the commit history into the spark-ify commit so we know what exactly was reverted or do you still want me to split it?

**Comment by spkal01** [comment]
Sure just add on sparkify commit

**Comment by Pyrtle93** [comment]
Is this better?
https://github.com/Pyrtle93/device_oneplus_lemonkebab/commit/2aef57b38734415d6d18c0d7d08d2dc8f07aa29f

**Comment by spkal01** [comment]
Status: Accepted
