### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by THERAD1** [Spark-Rom/official_devices#79]
## Device you want to apply for
```
OnePlus 9/9Pro Series - lemonade, lemonadep
```

## Device tree sources

```
https://github.com/SparkOS-lemonade-lemonadep
```

## Link to the platform where you have released your unofficial build
```
https://t.me/OnePlus9chat
```

## Other ROM's you maintain officially or unofficially
```
Official = Havoc A11 & A12(soon), Nameless A12, Ancient Rom A11 & A12.
previously maintained Officially = Shapeshift and Project Sakura for both Op6 and Op9
Unofficially = SparkOS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
about 3 Years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@NeoTheSavage
```

**Comment by spkal01** [comment]
Status: Rejected 

1 your common bringup commit has useless overlays not needed for a12
2 Why would you have maintainer prop both on system and product prop

**Comment by THERAD1** [comment]
The prop is because you have outdated info on your docs bring up page?
Found accurate info in the chat and forgot to drop the other one, but hey
it's ok. Which overlays are suggesting are useless exactly?
