### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Ardjlon** [Spark-Rom/official_devices#82]
## Device you want to apply for
```
POCO X3 NFC (Surya and Karna)
```

## Device tree sources

```
https://github.com/Ardjlon/android_device_xiaomi_surya
https://github.com/Ardjlon/android_kernel_xiaomi_surya
https://github.com/Ardjlon/android_vendor_xiaomi_surya
```

## Link to the platform where you have released your unofficial build
```
https://t.me/evoxskbugs/14228
```

## Other ROM's you maintain officially or unofficially
```
Ancient OS official
Evolution X unofficial
```

## Bugs on unofficial build
```
So far none
```

## How long have you been building for?
```
9 years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Ardjlon
```

**Comment by spkal01** [comment]
Status: Rejected 
Reasons: 1 why have you imported the whole freaking sepolicy on your tree ?
2 the dt should only be adapted to spark the android products should only have spark entries

**Comment by Ardjlon** [comment]
> Status: Rejected Reasons: 1 why have you imported the whole freaking sepolicy on your tree ? 2 the dt should only be adapted to spark the android products should only have spark entries

Thanks for your feedback sir.
The sepolicy is practically the same in my dt, only that I manage it in different folders to manage it with different ROMS, it's the only reason it looks like it's been imported, but it's not.
I will make another branch, and apply again

**Comment by spkal01** [comment]
Great 👍
