### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by NamCap25** [Spark-Rom/official_devices#83]
## Device you want to apply for
Redmi note 11 4G
Your device name and codename
Specs/Spesn

## Device tree sources

```
https://github.com/Adamjami/android_device_xiaomi_spes
https://github.com/Adamjami/kernel_xiaomi_spes_header
https://gitlab.com/Adamjami/vendor_xiaomi_spes_header
```

## Link to the platform where you have released your unofficial build 
Sourceforge 
Insert here
https://sourceforge.net/projects/los-spes/files/LOS/Spark-12.3-UNOFFICIAL-spes-20220521-gapps.zip/download

## Other ROM's you maintain officially or unofficially
Project Arcana UNOFFICIAL, PixelPlusUi UNOFFICIAL

## Bugs on unofficial build
Offline charging, proximity sensor but I have to revert a commit since it was working days ago. 

## How long have you been building for?
```
Weeks/Months/Years
Weeks

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
I read everything properly and I want to humbly ask for an exception to maintain even tho I am having proximity sensor bug that I am working on fixing.

```

## SELinux status?

Enforcing.

## Are you using a prebuilt kernel? If yes, why?
```
Yes, because Xiaomi didn't release kernel source yet for this device.
```

### Telegram username

Your Telegram username
@namispep

**Comment by spkal01** [comment]
Status : Rejected no contributions

**Comment by NamCap25** [comment]
Please can I ask about the " no contribution" meaning?

**Comment by spkal01** [comment]
It means that you haven't done any significant change on top of the base dt

**Comment by NamCap25** [comment]
Oh that's right, actually I contributed directly to the fix of stuff on the
tree of my friend jabiyef, we fixed and optimized the tree together for
easy adaption+ bug fixed proximity sensor, swapped Audio hals and deleted
useless init entries and as well, committed goodix fingerprint issue. I am
working on offline charging bug and I send him to apply it to his tree. I
forked the tree that I already contributed too much into. How can I
contribute more ? I am not competing with him

**Comment by spkal01** [comment]
Your GitHub history should show that you have done contributions to the device trees

**Comment by NamCap25** [comment]
I am asking for you to humbly allow me to maintain spark officially for
spes/spesn, me and jabiyef are good friends and we are doing most of the
job on telegram, we discuss and he try the instructions I send on his tree,
I test and vice versa sometimes, I send him the codes to apply on his tree
via telegram, I can show proof screenshots, but it won't actually show on
GitHub right? It's impossible to show what I contributed with via telegram.
Mainly because I was using my phone most of the time, now that I got a PC
with a server again, I wanna get a chance to build for spark and
contribute, I am really enjoying the unofficial build I made, I even fixed
proximity for it, I guided jabiyef to fix it on his tree actually, that I
forked just before submitting to this maintainer-ship. It's up to you, my
best regards.

**Comment by spkal01** [comment]
I would really like to give you maintainership but I don't have anything backing up your claim as your GitHub account is only like a month old

**Comment by NamCap25** [comment]
Uhm, thanks for your patience, actually I talked to jabiyef right now and
he said he also forked from dblenk the base tree and he didn't need that
much of changements to apply for crdroid maintainer-ship back then, but at
least with this tree that we both worked on, everything is almost perfect,
there's no room for any other improvement other than fixing offline
charging bug, which I will fix tonight or tomorrow hopefully in next build
and I can guarantee you that, the people loving spark os in our community
are alot, some are just waiting for me to become official and excited for
it, " like an insurance so they daily drive it with confidence". And the
Best guarantee for you, is the stability of this ROM that will maintain the
reputation of Spark OS as one of the best ROMs nowadays.
