### ISSUE TITLE
New maintainer For Spes/Spesn

### ISSUE THREAD

**Issue by NamCap25** [Spark-Rom/official_devices#84]
## Device you want to apply for
```
Your device name and codename
Spes/Spesn

## Device tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```
https://github.com/Adamjami/android_device_xiaomi_spes
https://github.com/Adamjami/kernel_xiaomi_spes_header
https://gitlab.com/Jabiyeff/android_vendor_xiaomi_spes
```

## Link to the platform where you have released your unofficial build
```
Insert here
https://sourceforge.net/projects/los-spes/files/LOS/

## Other ROM's you maintain officially or unofficially
```
Insert here
Project Arcana and PPUI but i'm deciding to maintain Spark Os 

## Bugs on unofficial build
```
Offline charging 
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing

## Are you using a prebuilt kernel? If yes, why?
```
Yes, because Xiaomi didn't release Kernel source yet. 
```

### Telegram username
Nam Cap
Your Telegram username
@namispep

**Comment by spkal01** [comment]
Status: Rejected duplicate
