### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Ardjlon** [Spark-Rom/official_devices#85]
## Device you want to apply for
```
POCO X3 NFC (Surya & Karna)
```

## Device tree sources

```
https://github.com/Ardjlon/android_device_xiaomi_surya/tree/spark
https://github.com/Ardjlon/android_kernel_xiaomi_surya
https://github.com/Ardjlon/vendor_surya
```

## Link to the platform where you have released your unofficial build
```
https://t.me/evoxskbugs/14228
```

## Other ROM's you maintain officially or unofficially
```
Ancient OS official
Evolution X unofficial
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
9 Years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Ardjlon
```

**Comment by spkal01** [comment]
As I said on your previous application issue you need to have only spark entries on your dt

https://github.com/Ardjlon/android_device_xiaomi_surya/blob/spark/evolution_surya.mk
https://github.com/Ardjlon/android_device_xiaomi_surya/blob/spark/ancient_surya.mk

**Comment by Ardjlon** [comment]
> As I said on your previous application issue you need to have only spark entries on your dt
> 
> https://github.com/Ardjlon/android_device_xiaomi_surya/blob/spark/evolution_surya.mk https://github.com/Ardjlon/android_device_xiaomi_surya/blob/spark/ancient_surya.mk

Done, please check again sir :D

**Comment by Ardjlon** [comment]
@spkal01 hello sir, any new?

**Comment by Ardjlon** [comment]
Hi, no answers? Please :D

**Comment by spkal01** [comment]
Hi sorry I was too busy lately I will let you know tomorrow
