### ISSUE TITLE
maintainer cepheus

### ISSUE THREAD

**Issue by tribual** [Spark-Rom/official_devices#92]
Device and codename: Xiaomi Mi 9 (cepheus)

Device tree:

- https://github.com/Spark-Devices/android_device_xiaomi_cepheus/tree/pyro

Kernel source:

- https://github.com/Spark-Devices/android_kernel_xiaomi_cepheus/tree/pyro

Vendor source:

- https://github.com/Spark-Devices/android_vendor_xiaomi_cepheus/tree/pyro

Reason for prebuilt kernel (if exists): not exist

Selinux: Enforcing

Safetynet status: Pass without Magisk

Telegram username: https://t.me/tribual

XDA Profile (if exists): no

**Comment by whyredfire** [comment]
Hi, unfortunately the linked device tree doesn't exist.

**Comment by spkal01** [comment]
> Hi, unfortunately the linked device tree doesn't exist.

Priv

**Comment by tribual** [comment]
not worth
