### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Vitorgl2003** [Spark-Rom/official_devices#95]
## Device you want to apply for
```
Xiaomi Redmi Note 7 (lavender) 
```

## Device tree sources

```
https://github.com/Spark-Devices/android_device_xiaomi_lavender/tree/pyro
https://github.com/Spark-Devices/kernel_xiaomi_lavender/tree/pyro
https://github.com/Spark-Devices/android_vendor_xiaomi_lavender/tree/pyro
```

## Link to the platform where you have released your unofficial build
```
https://mega.nz/file/Zw9wxQga#G5QoRAnDiy8fvXdQhe0Q2nMNa3koabYpa7bPp8UiOEM
```

## Other ROM's you maintain officially or unofficially
```
Awaken and Havoc (Officialy).
```

## Bugs on unofficial build
```
None at moment.
```

## How long have you been building for?
```
1 year.
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@bitortheaddicted
```

**Comment by whyredfire** [comment]
Hi, while reviewing your application I found few things that you can improve upon.

1. Drop pixel charger from device tree and use the resources from spark vendor
2. Cleanup unused QTI bluetooth files
3. Nuke this unused call [here](https://github.com/Spark-Devices/android_device_xiaomi_lavender/blob/d9313c203200bcdd1d4c686e9fabf97ca0c2e289/device.mk#L76)
4. Build APN config from spark vendor
5. Don't build remove packages, spark gms doesn't have any of the stuff you'd want to remove
6. Drop reorder blob script from device tree, it has been moved to tools/extract-utils
7. Revert [this ](https://github.com/Spark-Devices/android_device_xiaomi_lavender/commit/a6a54353ada6f50b344c4618bb79c83218bfe151)commit, we're already on Android 13 and we've that by default
8. Smart pixels feature is useless on devices with IPS LCD displays, drop overlays for it

Can you explain what [this ](https://github.com/Spark-Devices/android_device_xiaomi_lavender/blob/e74ec5305aa46f9a8ba89b4ba2fb773bf756e150/device.mk#L240-L243)is for?

**Comment by Vitorgl2003** [comment]
Hi, please check right branch, on application I said pyro branch, not spark branch 😁
On pyro branch point 3, 4, 7 are solved as you can see [here](https://github.com/Spark-Devices/android_device_xiaomi_lavender/commit/12dbddd0b19e2abd3082b1e419e95642abc706ee).
About point 1, 2, 5 and 8 I will fix.
About AB ota updater, that hal is needed for devices with AB partition since this device tree was before a sdm660 common with devices with AB and only A partition, as well lavender don't have a real AB partition so it's redundant and can be nuked, I will do it as well.

**Comment by Vitorgl2003** [comment]
Hi, all should be fine now, please review my application on pyro branch.

**Comment by whyredfire** [comment]
Perfect.
