### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by chuspita** [Spark-Rom/official_devices#96]
## Device you want to apply for
```
Xiaomi Redmi Note 10 Pro (Sweet)
```

## Device tree sources

```
https://github.com/chuspita/12_device_xiaomi_sweet
https://github.com/chuspita/12_device_xiaomi_sm6150-common
https://github.com/vantoman/kernel_xiaomi_sm6150/tree/courbet-12.1
https://github.com/chuspita/vendor_xiaomi
```

## Link to the platform where you have released your unofficial build
```
[Insert here](https://sourceforge.net/projects/sweet-roms/files/)
```

## Other ROM's you maintain officially or unofficially
```
CherishOS, Xtended, Evox (personal use only)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
a couple of years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
[Your Telegram username](https://t.me/franlop77)
```

**Comment by spkal01** [comment]
Hey are you applying for a13 ? or a12

**Comment by chuspita** [comment]
Until yesterday I was with A12, but now as you have uploaded the sources of A13, from now on I start to build Spark A13

**Comment by spkal01** [comment]
We don't accept maintainers for a12. Once you have booted spark a13 you can re apply

**Comment by chuspita** [comment]
ok...building now. Thank you
