### ISSUE TITLE
Veux Maintainer

### ISSUE THREAD

**Issue by neikos4962** [Spark-Rom/official_devices#98]
## Device you want to apply for
```
Your device name and codename
Xiaomi Redmi Note 11 Pro 5G (veux)

## Device tree sources

* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```
https://github.com/Spark-Devices/device_xiaomi_veux
https://github.com/Spark-Devices/vendor_xiaomi_veux
https://github.com/Spark-Devices/kernel_xiaomi_sm8350

```

## Link to the platform where you have released your unofficial build
```
https://t.me/PocoX4ProUpdates

## Other ROM's you maintain officially or unofficially
```
Derpfest (official)

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 year

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@semialex16

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
