### ISSUE TITLE
Chuspita

### ISSUE THREAD

**Issue by chuspita** [Spark-Rom/official_devices#99]
## Device you want to apply for
```
Xiaomi Redmi Note 10 Pro (Sweet)
```

## Device tree sources

```
https://github.com/chuspita/13_device-xiaomi-sweet
https://github.com/chuspita/13-device_xiaomi_sm6150-common
https://github.com/vantoman/kernel_xiaomi_sm6150/tree/courbet-12.1
https://github.com/chuspita/13_vendor_xiaomi
```

## Link to the platform where you have released your unofficial build
```
[Insert here](https://sourceforge.net/projects/sweet-roms/files/)
```

## Other ROM's you maintain officially or unofficially
```
CherisOS, Xtended, Evox (personal use only)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
A couple of years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
[Your Telegram username](https://t.me/franlop77)
```

**Comment by whyredfire** [comment]
How long have you been building for?

**Comment by chuspita** [comment]
about two years or so, but until now it was only for my personal use

**Comment by whyredfire** [comment]
You github account doesn't seem to have any history.

**Comment by chuspita** [comment]
If right. I hadn't decided to put my tree on github, because before I didn't publish any ROMS, now I'm publishing some unofficial ROMS, doing tests, learning new things and always trying to improve the device. Now I see myself ready to maintain an official ROM, so now I have my git operational.

**Comment by chuspita** [comment]
I am always in contact with another maintainer of Sweet, his Nick is jimgsey, he maintains Ricedroid on this device, he is my how to say it... he is my mentor. My first compilation was a ROM called ZenX-OS, its author was a dev called Zenixxx, well we are talking about A10 if I remember correctly

**Comment by ghost** [comment]
Why not put these two commit (https://github.com/chuspita/13_device-xiaomi-sweet/commit/5d41aff39cf84b293409544fb588c1ec83eeb8ce /// https://github.com/chuspita/13-device_xiaomi_sm6150-common/commit/189a879c4ed9f89a8aff49496bfbe428fc0b7285) in one only tree? Preferably the common tree. Also, your vendor is missing com.qti.node.watermark.so patched.

I noticed that you also have no knowledge about git. 

Why not study a little bit before applying?

If it were up to me, you would be rejected!

**Comment by ghost** [comment]
Why https://github.com/chuspita/13_device-xiaomi-sweet/commit/8d4440d988df8abab7e0b240554840aee8bac0aa ?? NewPipe should be optional for the user, it should not force them to use it.

**Comment by ghost** [comment]
where is the link to the common tree vendor?

**Comment by spkal01** [comment]
> where is the link to the common tree vendor?

Vendor Xiaomi contains both

**Comment by chuspita** [comment]
https://github.com/chuspita/13_vendor_xiaomi/tree/13.0/sm6150-common

**Comment by ghost** [comment]
> Why not put these two commit ([chuspita/13_device-xiaomi-sweet@5d41aff](https://github.com/chuspita/13_device-xiaomi-sweet/commit/5d41aff39cf84b293409544fb588c1ec83eeb8ce) /// [chuspita/13-device_xiaomi_sm6150-common@189a879](https://github.com/chuspita/13-device_xiaomi_sm6150-common/commit/189a879c4ed9f89a8aff49496bfbe428fc0b7285)) in one only tree? Preferably the common tree. Also, your vendor is missing com.qti.node.watermark.so patched.
> 
> I noticed that you also have no knowledge about git.
> 
> Why not study a little bit before applying?
> 
> If it were up to me, you would be rejected!

Sorry about the "com.qti.node.watermark.so" I just saw that it has (https://github.com/chuspita/13_vendor_xiaomi/commit/89eacdc7acc5c52ca200457c5ac81ca0c9970976)

**Comment by ghost** [comment]
> > where is the link to the common tree vendor?
> 
> Vendor Xiaomi contains both

I'm blind, srry

**Comment by ghost** [comment]
> https://github.com/chuspita/13_vendor_xiaomi/tree/13.0/sm6150-common

Yeah, I just saw, I'm half blind lol

**Comment by chuspita** [comment]
enzo19976 ... since you're unfriendly to me, I'm going to be unfriendly to you...I put newpipe because it's an unofficial rom and I put whatever I want, newpipe is a vanced type app...and the above, the tree are not mine as you have to suppose... you managed to make me want to keep spark, thanks for taking away my illusion

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
